name: Main push

on:
  push:
    branches: [ main ]

jobs:
  buildAndDeploy:
    runs-on: windows-latest
    env:
      TF_BUILD: true
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
    - name: Restore dependencies
      run: dotnet restore ./src
    - name: Build
      run: dotnet build ./src --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal ./src
    - name: Publish to NuGet
      continue-on-error: true
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: src/logger/Autabee.Utility.Logger.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          VERSION_FILE_PATH: common.props
          INCLUDE_SYMBOLS: true
          NO_BUILD: true
    - name: Publish to NuGet
      continue-on-error: true
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: src/Logger.xUnit/Autabee.Utility.Logger.xUnit.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          VERSION_FILE_PATH: common.props
          INCLUDE_SYMBOLS: true
          NO_BUILD: true
